```{r setup, message = FALSE}
library(tidyverse)
```

# Reading in Overall Data
```{r, echo=FALSE}

BRTotal <- read.csv("2019_20_BRTotal.csv")
# Changing a few variable names
BRTotal <- BRTotal %>% rename(Player = ï..Player,
                              FG_P = FG.,
                              FT_P = FT.,
                              X3P_P = X3P.,
                              X2P_P = X2P.,
                              eFG_P = eFG.)
```

# PG Overall Stats
``` {r pg.overall}
#Finding the Stats for PGs
PG_Data <- BRTotal %>% filter(Pos == "PG") %>% drop_na()
# Adding the absolute value Differentials for each player from the medians
PG_Data <- PG_Data %>%
            mutate(Age.Diff = abs(PG_Data$Age - median(PG_Data$Age)),
                   G.Diff = abs(PG_Data$G - median(PG_Data$G)),
                   GS.Diff = abs(PG_Data$GS - median(PG_Data$GS)),
                   MP.Diff = abs(PG_Data$MP - median(PG_Data$MP)),
                   FG.Diff = abs(PG_Data$FG - median(PG_Data$FG)), 
                   FGA.Diff = abs(PG_Data$FGA - median(PG_Data$FGA)),
                   X3P.Diff = abs(PG_Data$X3P - median(PG_Data$X3P)),
                   X3PA.Diff = abs(PG_Data$X3PA- median(PG_Data$X3PA)),
                   X2P.Diff = abs(PG_Data$X2P - median(PG_Data$X2P)),
                   X2PA.Diff =abs(PG_Data$X2PA - median(PG_Data$X2PA)),
                   FT.Diff = abs(PG_Data$FT - median(PG_Data$FT)),
                   FTA.Diff =abs(PG_Data$FTA - median(PG_Data$FTA)),
                   TRB.Diff =abs(PG_Data$TRB - median(PG_Data$TRB)),
                   AST.Diff =abs(PG_Data$AST - median(PG_Data$AST)), 
                   STL.Diff =abs(PG_Data$STL - median(PG_Data$STL)), 
                   BLK.Diff =abs(PG_Data$BLK - median(PG_Data$BLK)),
                   TOV.Diff =abs(PG_Data$TOV - median(PG_Data$TOV)),
                   PF.Diff =abs(PG_Data$PF - median(PG_Data$PF)),
                   PTS.Diff =abs(PG_Data$PTS - median(PG_Data$PTS)),
                   FG_P.Diff =abs(PG_Data$FG_P - median(PG_Data$FG_P)),
                   FT_P.Diff =abs(PG_Data$FT_P - median(PG_Data$FT_P)),
                   X3P_P.Diff =abs(PG_Data$X3P_P - median(PG_Data$X3P_P)),
                   X2P_P.Diff =abs(PG_Data$X2P_P - median(PG_Data$X2P_P)),
                   eFG_P.Diff =abs(PG_Data$eFG_P - median(PG_Data$eFG_P)), 
                   ORB.Diff = abs(PG_Data$ORB - median(PG_Data$ORB)),
                   DRB.Diff = abs(PG_Data$DRB - median(PG_Data$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
PG_Data <- PG_Data %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)

```

# PG Stats Per Game

```{r pg.g, echo=FALSE}
#Creating a dataframe with the data divided by Games Played
PG_Filter_G <- select(PG_Data,MP:DRB.Diff) 

PG_Stats_G <- PG_Filter_G %>% mutate_if(is.numeric, funs(./PG_Data$G))

PG_Data_G <- PG_Stats_G %>%
            mutate(MP.Diff = abs(PG_Stats_G$MP - median(PG_Stats_G$MP)),
                   FG.Diff = abs(PG_Stats_G$FG - median(PG_Stats_G$FG)), 
                   FGA.Diff = abs(PG_Stats_G$FGA - median(PG_Stats_G$FGA)),
                   X3P.Diff = abs(PG_Stats_G$X3P - median(PG_Stats_G$X3P)),
                   X3PA.Diff = abs(PG_Stats_G$X3PA- median(PG_Stats_G$X3PA)),
                   X2P.Diff = abs(PG_Stats_G$X2P - median(PG_Stats_G$X2P)),
                   X2PA.Diff =abs(PG_Stats_G$X2PA - median(PG_Stats_G$X2PA)),
                   FT.Diff = abs(PG_Stats_G$FT - median(PG_Stats_G$FT)),
                   FTA.Diff =abs(PG_Stats_G$FTA - median(PG_Stats_G$FTA)),
                   TRB.Diff =abs(PG_Stats_G$TRB - median(PG_Stats_G$TRB)),
                   AST.Diff =abs(PG_Stats_G$AST - median(PG_Stats_G$AST)), 
                   STL.Diff =abs(PG_Stats_G$STL - median(PG_Stats_G$STL)), 
                   BLK.Diff =abs(PG_Stats_G$BLK - median(PG_Stats_G$BLK)),
                   TOV.Diff =abs(PG_Stats_G$TOV - median(PG_Stats_G$TOV)),
                   PF.Diff =abs(PG_Stats_G$PF - median(PG_Stats_G$PF)),
                   PTS.Diff =abs(PG_Stats_G$PTS - median(PG_Stats_G$PTS)),
                   FG_P.Diff =abs(PG_Stats_G$FG_P - median(PG_Stats_G$FG_P)),
                   FT_P.Diff =abs(PG_Stats_G$FT_P - median(PG_Stats_G$FT_P)),
                   X3P_P.Diff =abs(PG_Stats_G$X3P_P - median(PG_Stats_G$X3P_P)),
                   X2P_P.Diff =abs(PG_Stats_G$X2P_P - median(PG_Stats_G$X2P_P)),
                   eFG_P.Diff =abs(PG_Stats_G$eFG_P - median(PG_Stats_G$eFG_P)), 
                   ORB.Diff = abs(PG_Stats_G$ORB - median(PG_Stats_G$ORB)),
                   DRB.Diff = abs(PG_Stats_G$DRB - median(PG_Stats_G$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
PG_Data_G <- mutate(PG_Data_G, 
                    Player = PG_Data$Player, 
                    Pos = PG_Data$Pos, 
                    Tm = PG_Data$Tm, 
                    Age = PG_Data$Age, 
                    Age.Diff = PG_Data$Age.Diff, 
                    G = PG_Data$G, 
                    G.Diff = PG_Data$G.Diff, 
                    GS = PG_Data$GS, 
                    GS.Diff = PG_Data$GS.Diff
                    )

PG_Data_G <- PG_Data_G %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

# PG Stats Per Minutes Played

```{r pg.mp, echo=FALSE}
#Creating a dataframe with the data divided by Minutes Played
PG_Filter_MP <- select(PG_Data,FG:DRB.Diff) 

PG_Stats_MP <- PG_Filter_MP %>% mutate_if(is.numeric, funs(./PG_Data$MP))

PG_Data_MP <- PG_Stats_MP %>%
            mutate(FG.Diff = abs(PG_Stats_MP$FG - median(PG_Stats_MP$FG)), 
                   FGA.Diff = abs(PG_Stats_MP$FGA - median(PG_Stats_MP$FGA)),
                   X3P.Diff = abs(PG_Stats_MP$X3P - median(PG_Stats_MP$X3P)),
                   X3PA.Diff = abs(PG_Stats_MP$X3PA- median(PG_Stats_MP$X3PA)),
                   X2P.Diff = abs(PG_Stats_MP$X2P - median(PG_Stats_MP$X2P)),
                   X2PA.Diff =abs(PG_Stats_MP$X2PA - median(PG_Stats_MP$X2PA)),
                   FT.Diff = abs(PG_Stats_MP$FT - median(PG_Stats_MP$FT)),
                   FTA.Diff =abs(PG_Stats_MP$FTA - median(PG_Stats_MP$FTA)),
                   TRB.Diff =abs(PG_Stats_MP$TRB - median(PG_Stats_MP$TRB)),
                   AST.Diff =abs(PG_Stats_MP$AST - median(PG_Stats_MP$AST)), 
                   STL.Diff =abs(PG_Stats_MP$STL - median(PG_Stats_MP$STL)), 
                   BLK.Diff =abs(PG_Stats_MP$BLK - median(PG_Stats_MP$BLK)),
                   TOV.Diff =abs(PG_Stats_MP$TOV - median(PG_Stats_MP$TOV)),
                   PF.Diff =abs(PG_Stats_MP$PF - median(PG_Stats_MP$PF)),
                   PTS.Diff =abs(PG_Stats_MP$PTS - median(PG_Stats_MP$PTS)),
                   FG_P.Diff =abs(PG_Stats_MP$FG_P - median(PG_Stats_MP$FG_P)),
                   FT_P.Diff =abs(PG_Stats_MP$FT_P - median(PG_Stats_MP$FT_P)),
                   X3P_P.Diff =abs(PG_Stats_MP$X3P_P - median(PG_Stats_MP$X3P_P)),
                   X2P_P.Diff =abs(PG_Stats_MP$X2P_P - median(PG_Stats_MP$X2P_P)),
                   eFG_P.Diff =abs(PG_Stats_MP$eFG_P - median(PG_Stats_MP$eFG_P)), 
                   ORB.Diff = abs(PG_Stats_MP$ORB - median(PG_Stats_MP$ORB)),
                   DRB.Diff = abs(PG_Stats_MP$DRB - median(PG_Stats_MP$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
PG_Data_MP <- mutate(PG_Data_MP, 
                    Player = PG_Data$Player, 
                    Pos = PG_Data$Pos, 
                    Tm = PG_Data$Tm, 
                    Age = PG_Data$Age, 
                    Age.Diff = PG_Data$Age.Diff, 
                    G = PG_Data$G, 
                    G.Diff = PG_Data$G.Diff, 
                    GS = PG_Data$GS, 
                    GS.Diff = PG_Data$GS.Diff,
                    MP = PG_Data$MP, 
                    MP.Diff = PG_Data$MP.Diff
                    )

PG_Data_MP <- PG_Data_MP %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```
# SG Overall Stats

``` {r sg.overall}
#Finding the Stats for PGs
SG_Data <- BRTotal %>% filter(Pos == "SG") %>% drop_na()
# Adding the absolute value Differentials for each player from the medians
SG_Data <- SG_Data %>%
            mutate(Age.Diff = abs(SG_Data$Age - median(SG_Data$Age)),
                   G.Diff = abs(SG_Data$G - median(SG_Data$G)),
                   GS.Diff = abs(SG_Data$GS - median(SG_Data$GS)),
                   MP.Diff = abs(SG_Data$MP - median(SG_Data$MP)),
                   FG.Diff = abs(SG_Data$FG - median(SG_Data$FG)), 
                   FGA.Diff = abs(SG_Data$FGA - median(SG_Data$FGA)),
                   X3P.Diff = abs(SG_Data$X3P - median(SG_Data$X3P)),
                   X3PA.Diff = abs(SG_Data$X3PA- median(SG_Data$X3PA)),
                   X2P.Diff = abs(SG_Data$X2P - median(SG_Data$X2P)),
                   X2PA.Diff =abs(SG_Data$X2PA - median(SG_Data$X2PA)),
                   FT.Diff = abs(SG_Data$FT - median(SG_Data$FT)),
                   FTA.Diff =abs(SG_Data$FTA - median(SG_Data$FTA)),
                   TRB.Diff =abs(SG_Data$TRB - median(SG_Data$TRB)),
                   AST.Diff =abs(SG_Data$AST - median(SG_Data$AST)), 
                   STL.Diff =abs(SG_Data$STL - median(SG_Data$STL)), 
                   BLK.Diff =abs(SG_Data$BLK - median(SG_Data$BLK)),
                   TOV.Diff =abs(SG_Data$TOV - median(SG_Data$TOV)),
                   PF.Diff =abs(SG_Data$PF - median(SG_Data$PF)),
                   PTS.Diff =abs(SG_Data$PTS - median(SG_Data$PTS)),
                   FG_P.Diff =abs(SG_Data$FG_P - median(SG_Data$FG_P)),
                   FT_P.Diff =abs(SG_Data$FT_P - median(SG_Data$FT_P)),
                   X3P_P.Diff =abs(SG_Data$X3P_P - median(SG_Data$X3P_P)),
                   X2P_P.Diff =abs(SG_Data$X2P_P - median(SG_Data$X2P_P)),
                   eFG_P.Diff =abs(SG_Data$eFG_P - median(SG_Data$eFG_P)), 
                   ORB.Diff = abs(SG_Data$ORB - median(SG_Data$ORB)),
                   DRB.Diff = abs(SG_Data$DRB - median(SG_Data$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
SG_Data <- SG_Data %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

# SG Stats Per Game

```{r sg.g, echo=FALSE}
#Creating a dataframe with the data divided by Games Played
SG_Filter_G <- select(SG_Data,MP:DRB.Diff) 

SG_Stats_G <- SG_Filter_G %>% mutate_if(is.numeric, funs(./SG_Data$G))

SG_Data_G <- SG_Stats_G %>%
            mutate(MP.Diff = abs(SG_Stats_G$MP - median(SG_Stats_G$MP)),
                   FG.Diff = abs(SG_Stats_G$FG - median(SG_Stats_G$FG)), 
                   FGA.Diff = abs(SG_Stats_G$FGA - median(SG_Stats_G$FGA)),
                   X3P.Diff = abs(SG_Stats_G$X3P - median(SG_Stats_G$X3P)),
                   X3PA.Diff = abs(SG_Stats_G$X3PA- median(SG_Stats_G$X3PA)),
                   X2P.Diff = abs(SG_Stats_G$X2P - median(SG_Stats_G$X2P)),
                   X2PA.Diff =abs(SG_Stats_G$X2PA - median(SG_Stats_G$X2PA)),
                   FT.Diff = abs(SG_Stats_G$FT - median(SG_Stats_G$FT)),
                   FTA.Diff =abs(SG_Stats_G$FTA - median(SG_Stats_G$FTA)),
                   TRB.Diff =abs(SG_Stats_G$TRB - median(SG_Stats_G$TRB)),
                   AST.Diff =abs(SG_Stats_G$AST - median(SG_Stats_G$AST)), 
                   STL.Diff =abs(SG_Stats_G$STL - median(SG_Stats_G$STL)), 
                   BLK.Diff =abs(SG_Stats_G$BLK - median(SG_Stats_G$BLK)),
                   TOV.Diff =abs(SG_Stats_G$TOV - median(SG_Stats_G$TOV)),
                   PF.Diff =abs(SG_Stats_G$PF - median(SG_Stats_G$PF)),
                   PTS.Diff =abs(SG_Stats_G$PTS - median(SG_Stats_G$PTS)),
                   FG_P.Diff =abs(SG_Stats_G$FG_P - median(SG_Stats_G$FG_P)),
                   FT_P.Diff =abs(SG_Stats_G$FT_P - median(SG_Stats_G$FT_P)),
                   X3P_P.Diff =abs(SG_Stats_G$X3P_P - median(SG_Stats_G$X3P_P)),
                   X2P_P.Diff =abs(SG_Stats_G$X2P_P - median(SG_Stats_G$X2P_P)),
                   eFG_P.Diff =abs(SG_Stats_G$eFG_P - median(SG_Stats_G$eFG_P)), 
                   ORB.Diff = abs(SG_Stats_G$ORB - median(SG_Stats_G$ORB)),
                   DRB.Diff = abs(SG_Stats_G$DRB - median(SG_Stats_G$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
SG_Data_G <- mutate(SG_Data_G, 
                    Player = SG_Data$Player, 
                    Pos = SG_Data$Pos, 
                    Tm = SG_Data$Tm, 
                    Age = SG_Data$Age, 
                    Age.Diff = SG_Data$Age.Diff, 
                    G = SG_Data$G, 
                    G.Diff = SG_Data$G.Diff, 
                    GS = SG_Data$GS, 
                    GS.Diff = SG_Data$GS.Diff
                    )

SG_Data_G <- SG_Data_G %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

# SG Stats Per Minutes Played

```{r sg.mp, echo=FALSE}
#Creating a dataframe with the data divided by Minutes Played
SG_Filter_MP <- select(SG_Data,FG:DRB.Diff) 

SG_Stats_MP <- SG_Filter_MP %>% mutate_if(is.numeric, funs(./SG_Data$MP))

SG_Data_MP <- SG_Stats_MP %>%
            mutate(FG.Diff = abs(SG_Stats_MP$FG - median(SG_Stats_MP$FG)), 
                   FGA.Diff = abs(SG_Stats_MP$FGA - median(SG_Stats_MP$FGA)),
                   X3P.Diff = abs(SG_Stats_MP$X3P - median(SG_Stats_MP$X3P)),
                   X3PA.Diff = abs(SG_Stats_MP$X3PA- median(SG_Stats_MP$X3PA)),
                   X2P.Diff = abs(SG_Stats_MP$X2P - median(SG_Stats_MP$X2P)),
                   X2PA.Diff =abs(SG_Stats_MP$X2PA - median(SG_Stats_MP$X2PA)),
                   FT.Diff = abs(SG_Stats_MP$FT - median(SG_Stats_MP$FT)),
                   FTA.Diff =abs(SG_Stats_MP$FTA - median(SG_Stats_MP$FTA)),
                   TRB.Diff =abs(SG_Stats_MP$TRB - median(SG_Stats_MP$TRB)),
                   AST.Diff =abs(SG_Stats_MP$AST - median(SG_Stats_MP$AST)), 
                   STL.Diff =abs(SG_Stats_MP$STL - median(SG_Stats_MP$STL)), 
                   BLK.Diff =abs(SG_Stats_MP$BLK - median(SG_Stats_MP$BLK)),
                   TOV.Diff =abs(SG_Stats_MP$TOV - median(SG_Stats_MP$TOV)),
                   PF.Diff =abs(SG_Stats_MP$PF - median(SG_Stats_MP$PF)),
                   PTS.Diff =abs(SG_Stats_MP$PTS - median(SG_Stats_MP$PTS)),
                   FG_P.Diff =abs(SG_Stats_MP$FG_P - median(SG_Stats_MP$FG_P)),
                   FT_P.Diff =abs(SG_Stats_MP$FT_P - median(SG_Stats_MP$FT_P)),
                   X3P_P.Diff =abs(SG_Stats_MP$X3P_P - median(SG_Stats_MP$X3P_P)),
                   X2P_P.Diff =abs(SG_Stats_MP$X2P_P - median(SG_Stats_MP$X2P_P)),
                   eFG_P.Diff =abs(SG_Stats_MP$eFG_P - median(SG_Stats_MP$eFG_P)), 
                   ORB.Diff = abs(SG_Stats_MP$ORB - median(SG_Stats_MP$ORB)),
                   DRB.Diff = abs(SG_Stats_MP$DRB - median(SG_Stats_MP$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
SG_Data_MP <- mutate(SG_Data_MP, 
                    Player = SG_Data$Player, 
                    Pos = SG_Data$Pos, 
                    Tm = SG_Data$Tm, 
                    Age = SG_Data$Age, 
                    Age.Diff = SG_Data$Age.Diff, 
                    G = SG_Data$G, 
                    G.Diff = SG_Data$G.Diff, 
                    GS = SG_Data$GS, 
                    GS.Diff = SG_Data$GS.Diff,
                    MP = SG_Data$MP, 
                    MP.Diff = SG_Data$MP.Diff
                    )

SG_Data_MP <- SG_Data_MP %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

# PG Overall Stats

``` {r sf.overall}
#Finding the Stats for PGs
SF_Data <- BRTotal %>% filter(Pos == "SF") %>% drop_na()
# Adding the absolute value Differentials for each player from the medians
SF_Data <- SF_Data %>%
            mutate(Age.Diff = abs(SF_Data$Age - median(SF_Data$Age)),
                   G.Diff = abs(SF_Data$G - median(SF_Data$G)),
                   GS.Diff = abs(SF_Data$GS - median(SF_Data$GS)),
                   MP.Diff = abs(SF_Data$MP - median(SF_Data$MP)),
                   FG.Diff = abs(SF_Data$FG - median(SF_Data$FG)), 
                   FGA.Diff = abs(SF_Data$FGA - median(SF_Data$FGA)),
                   X3P.Diff = abs(SF_Data$X3P - median(SF_Data$X3P)),
                   X3PA.Diff = abs(SF_Data$X3PA- median(SF_Data$X3PA)),
                   X2P.Diff = abs(SF_Data$X2P - median(SF_Data$X2P)),
                   X2PA.Diff =abs(SF_Data$X2PA - median(SF_Data$X2PA)),
                   FT.Diff = abs(SF_Data$FT - median(SF_Data$FT)),
                   FTA.Diff =abs(SF_Data$FTA - median(SF_Data$FTA)),
                   TRB.Diff =abs(SF_Data$TRB - median(SF_Data$TRB)),
                   AST.Diff =abs(SF_Data$AST - median(SF_Data$AST)), 
                   STL.Diff =abs(SF_Data$STL - median(SF_Data$STL)), 
                   BLK.Diff =abs(SF_Data$BLK - median(SF_Data$BLK)),
                   TOV.Diff =abs(SF_Data$TOV - median(SF_Data$TOV)),
                   PF.Diff =abs(SF_Data$PF - median(SF_Data$PF)),
                   PTS.Diff =abs(SF_Data$PTS - median(SF_Data$PTS)),
                   FG_P.Diff =abs(SF_Data$FG_P - median(SF_Data$FG_P)),
                   FT_P.Diff =abs(SF_Data$FT_P - median(SF_Data$FT_P)),
                   X3P_P.Diff =abs(SF_Data$X3P_P - median(SF_Data$X3P_P)),
                   X2P_P.Diff =abs(SF_Data$X2P_P - median(SF_Data$X2P_P)),
                   eFG_P.Diff =abs(SF_Data$eFG_P - median(SF_Data$eFG_P)), 
                   ORB.Diff = abs(SF_Data$ORB - median(SF_Data$ORB)),
                   DRB.Diff = abs(SF_Data$DRB - median(SF_Data$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
SF_Data <- SF_Data %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

# PG Stats Per Game

```{r sf.g, echo=FALSE}
#Creating a dataframe with the data divided by Games Played
SF_Filter_G <- select(SF_Data,MP:DRB.Diff) 

SF_Stats_G <- SF_Filter_G %>% mutate_if(is.numeric, funs(./SF_Data$G))

SF_Data_G <- SF_Stats_G %>%
            mutate(MP.Diff = abs(SF_Stats_G$MP - median(SF_Stats_G$MP)),
                   FG.Diff = abs(SF_Stats_G$FG - median(SF_Stats_G$FG)), 
                   FGA.Diff = abs(SF_Stats_G$FGA - median(SF_Stats_G$FGA)),
                   X3P.Diff = abs(SF_Stats_G$X3P - median(SF_Stats_G$X3P)),
                   X3PA.Diff = abs(SF_Stats_G$X3PA- median(SF_Stats_G$X3PA)),
                   X2P.Diff = abs(SF_Stats_G$X2P - median(SF_Stats_G$X2P)),
                   X2PA.Diff =abs(SF_Stats_G$X2PA - median(SF_Stats_G$X2PA)),
                   FT.Diff = abs(SF_Stats_G$FT - median(SF_Stats_G$FT)),
                   FTA.Diff =abs(SF_Stats_G$FTA - median(SF_Stats_G$FTA)),
                   TRB.Diff =abs(SF_Stats_G$TRB - median(SF_Stats_G$TRB)),
                   AST.Diff =abs(SF_Stats_G$AST - median(SF_Stats_G$AST)), 
                   STL.Diff =abs(SF_Stats_G$STL - median(SF_Stats_G$STL)), 
                   BLK.Diff =abs(SF_Stats_G$BLK - median(SF_Stats_G$BLK)),
                   TOV.Diff =abs(SF_Stats_G$TOV - median(SF_Stats_G$TOV)),
                   PF.Diff =abs(SF_Stats_G$PF - median(SF_Stats_G$PF)),
                   PTS.Diff =abs(SF_Stats_G$PTS - median(SF_Stats_G$PTS)),
                   FG_P.Diff =abs(SF_Stats_G$FG_P - median(SF_Stats_G$FG_P)),
                   FT_P.Diff =abs(SF_Stats_G$FT_P - median(SF_Stats_G$FT_P)),
                   X3P_P.Diff =abs(SF_Stats_G$X3P_P - median(SF_Stats_G$X3P_P)),
                   X2P_P.Diff =abs(SF_Stats_G$X2P_P - median(SF_Stats_G$X2P_P)),
                   eFG_P.Diff =abs(SF_Stats_G$eFG_P - median(SF_Stats_G$eFG_P)), 
                   ORB.Diff = abs(SF_Stats_G$ORB - median(SF_Stats_G$ORB)),
                   DRB.Diff = abs(SF_Stats_G$DRB - median(SF_Stats_G$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
SF_Data_G <- mutate(SF_Data_G, 
                    Player = SF_Data$Player, 
                    Pos = SF_Data$Pos, 
                    Tm = SF_Data$Tm, 
                    Age = SF_Data$Age, 
                    Age.Diff = SF_Data$Age.Diff, 
                    G = SF_Data$G, 
                    G.Diff = SF_Data$G.Diff, 
                    GS = SF_Data$GS, 
                    GS.Diff = SF_Data$GS.Diff
                    )

SF_Data_G <- SF_Data_G %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

# PG Stats Per Minutes Played

```{r sf.mp, echo=FALSE}
#Creating a dataframe with the data divided by Minutes Played
SF_Filter_MP <- select(SF_Data,FG:DRB.Diff) 

SF_Stats_MP <- SF_Filter_MP %>% mutate_if(is.numeric, funs(./SF_Data$MP))

SF_Data_MP <- SF_Stats_MP %>%
            mutate(FG.Diff = abs(SF_Stats_MP$FG - median(SF_Stats_MP$FG)), 
                   FGA.Diff = abs(SF_Stats_MP$FGA - median(SF_Stats_MP$FGA)),
                   X3P.Diff = abs(SF_Stats_MP$X3P - median(SF_Stats_MP$X3P)),
                   X3PA.Diff = abs(SF_Stats_MP$X3PA- median(SF_Stats_MP$X3PA)),
                   X2P.Diff = abs(SF_Stats_MP$X2P - median(SF_Stats_MP$X2P)),
                   X2PA.Diff =abs(SF_Stats_MP$X2PA - median(SF_Stats_MP$X2PA)),
                   FT.Diff = abs(SF_Stats_MP$FT - median(SF_Stats_MP$FT)),
                   FTA.Diff =abs(SF_Stats_MP$FTA - median(SF_Stats_MP$FTA)),
                   TRB.Diff =abs(SF_Stats_MP$TRB - median(SF_Stats_MP$TRB)),
                   AST.Diff =abs(SF_Stats_MP$AST - median(SF_Stats_MP$AST)), 
                   STL.Diff =abs(SF_Stats_MP$STL - median(SF_Stats_MP$STL)), 
                   BLK.Diff =abs(SF_Stats_MP$BLK - median(SF_Stats_MP$BLK)),
                   TOV.Diff =abs(SF_Stats_MP$TOV - median(SF_Stats_MP$TOV)),
                   PF.Diff =abs(SF_Stats_MP$PF - median(SF_Stats_MP$PF)),
                   PTS.Diff =abs(SF_Stats_MP$PTS - median(SF_Stats_MP$PTS)),
                   FG_P.Diff =abs(SF_Stats_MP$FG_P - median(SF_Stats_MP$FG_P)),
                   FT_P.Diff =abs(SF_Stats_MP$FT_P - median(SF_Stats_MP$FT_P)),
                   X3P_P.Diff =abs(SF_Stats_MP$X3P_P - median(SF_Stats_MP$X3P_P)),
                   X2P_P.Diff =abs(SF_Stats_MP$X2P_P - median(SF_Stats_MP$X2P_P)),
                   eFG_P.Diff =abs(SF_Stats_MP$eFG_P - median(SF_Stats_MP$eFG_P)), 
                   ORB.Diff = abs(SF_Stats_MP$ORB - median(SF_Stats_MP$ORB)),
                   DRB.Diff = abs(SF_Stats_MP$DRB - median(SF_Stats_MP$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
SF_Data_MP <- mutate(SF_Data_MP, 
                    Player = SF_Data$Player, 
                    Pos = SF_Data$Pos, 
                    Tm = SF_Data$Tm, 
                    Age = SF_Data$Age, 
                    Age.Diff = SF_Data$Age.Diff, 
                    G = SF_Data$G, 
                    G.Diff = SF_Data$G.Diff, 
                    GS = SF_Data$GS, 
                    GS.Diff = SF_Data$GS.Diff,
                    MP = SF_Data$MP, 
                    MP.Diff = SF_Data$MP.Diff
                    )

SF_Data_MP <- SF_Data_MP %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```
# PF Overall Stats
``` {r pf.overall}
#Finding the Stats for PFs
PF_Data <- BRTotal %>% filter(Pos == "PF") %>% drop_na()
# Adding the absolute value Differentials for each player from the medians
PF_Data <- PF_Data %>%
            mutate(Age.Diff = abs(PF_Data$Age - median(PF_Data$Age)),
                   G.Diff = abs(PF_Data$G - median(PF_Data$G)),
                   GS.Diff = abs(PF_Data$GS - median(PF_Data$GS)),
                   MP.Diff = abs(PF_Data$MP - median(PF_Data$MP)),
                   FG.Diff = abs(PF_Data$FG - median(PF_Data$FG)), 
                   FGA.Diff = abs(PF_Data$FGA - median(PF_Data$FGA)),
                   X3P.Diff = abs(PF_Data$X3P - median(PF_Data$X3P)),
                   X3PA.Diff = abs(PF_Data$X3PA- median(PF_Data$X3PA)),
                   X2P.Diff = abs(PF_Data$X2P - median(PF_Data$X2P)),
                   X2PA.Diff =abs(PF_Data$X2PA - median(PF_Data$X2PA)),
                   FT.Diff = abs(PF_Data$FT - median(PF_Data$FT)),
                   FTA.Diff =abs(PF_Data$FTA - median(PF_Data$FTA)),
                   TRB.Diff =abs(PF_Data$TRB - median(PF_Data$TRB)),
                   AST.Diff =abs(PF_Data$AST - median(PF_Data$AST)), 
                   STL.Diff =abs(PF_Data$STL - median(PF_Data$STL)), 
                   BLK.Diff =abs(PF_Data$BLK - median(PF_Data$BLK)),
                   TOV.Diff =abs(PF_Data$TOV - median(PF_Data$TOV)),
                   PF.Diff =abs(PF_Data$PF - median(PF_Data$PF)),
                   PTS.Diff =abs(PF_Data$PTS - median(PF_Data$PTS)),
                   FG_P.Diff =abs(PF_Data$FG_P - median(PF_Data$FG_P)),
                   FT_P.Diff =abs(PF_Data$FT_P - median(PF_Data$FT_P)),
                   X3P_P.Diff =abs(PF_Data$X3P_P - median(PF_Data$X3P_P)),
                   X2P_P.Diff =abs(PF_Data$X2P_P - median(PF_Data$X2P_P)),
                   eFG_P.Diff =abs(PF_Data$eFG_P - median(PF_Data$eFG_P)), 
                   ORB.Diff = abs(PF_Data$ORB - median(PF_Data$ORB)),
                   DRB.Diff = abs(PF_Data$DRB - median(PF_Data$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
PF_Data <- PF_Data %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)

```

# PF Stats Per Game

```{r pf.g, echo=FALSE}
#Creating a dataframe with the data divided by Games Played
PF_Filter_G <- select(PF_Data,MP:DRB.Diff) 

PF_Stats_G <- PF_Filter_G %>% mutate_if(is.numeric, funs(./PF_Data$G))

PF_Data_G <- PF_Stats_G %>%
            mutate(MP.Diff = abs(PF_Stats_G$MP - median(PF_Stats_G$MP)),
                   FG.Diff = abs(PF_Stats_G$FG - median(PF_Stats_G$FG)), 
                   FGA.Diff = abs(PF_Stats_G$FGA - median(PF_Stats_G$FGA)),
                   X3P.Diff = abs(PF_Stats_G$X3P - median(PF_Stats_G$X3P)),
                   X3PA.Diff = abs(PF_Stats_G$X3PA- median(PF_Stats_G$X3PA)),
                   X2P.Diff = abs(PF_Stats_G$X2P - median(PF_Stats_G$X2P)),
                   X2PA.Diff =abs(PF_Stats_G$X2PA - median(PF_Stats_G$X2PA)),
                   FT.Diff = abs(PF_Stats_G$FT - median(PF_Stats_G$FT)),
                   FTA.Diff =abs(PF_Stats_G$FTA - median(PF_Stats_G$FTA)),
                   TRB.Diff =abs(PF_Stats_G$TRB - median(PF_Stats_G$TRB)),
                   AST.Diff =abs(PF_Stats_G$AST - median(PF_Stats_G$AST)), 
                   STL.Diff =abs(PF_Stats_G$STL - median(PF_Stats_G$STL)), 
                   BLK.Diff =abs(PF_Stats_G$BLK - median(PF_Stats_G$BLK)),
                   TOV.Diff =abs(PF_Stats_G$TOV - median(PF_Stats_G$TOV)),
                   PF.Diff =abs(PF_Stats_G$PF - median(PF_Stats_G$PF)),
                   PTS.Diff =abs(PF_Stats_G$PTS - median(PF_Stats_G$PTS)),
                   FG_P.Diff =abs(PF_Stats_G$FG_P - median(PF_Stats_G$FG_P)),
                   FT_P.Diff =abs(PF_Stats_G$FT_P - median(PF_Stats_G$FT_P)),
                   X3P_P.Diff =abs(PF_Stats_G$X3P_P - median(PF_Stats_G$X3P_P)),
                   X2P_P.Diff =abs(PF_Stats_G$X2P_P - median(PF_Stats_G$X2P_P)),
                   eFG_P.Diff =abs(PF_Stats_G$eFG_P - median(PF_Stats_G$eFG_P)), 
                   ORB.Diff = abs(PF_Stats_G$ORB - median(PF_Stats_G$ORB)),
                   DRB.Diff = abs(PF_Stats_G$DRB - median(PF_Stats_G$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
PF_Data_G <- mutate(PF_Data_G, 
                    Player = PF_Data$Player, 
                    Pos = PF_Data$Pos, 
                    Tm = PF_Data$Tm, 
                    Age = PF_Data$Age, 
                    Age.Diff = PF_Data$Age.Diff, 
                    G = PF_Data$G, 
                    G.Diff = PF_Data$G.Diff, 
                    GS = PF_Data$GS, 
                    GS.Diff = PF_Data$GS.Diff
                    )

PF_Data_G <- PF_Data_G %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

# PF Stats Per Minutes Played

```{r pf.mp, echo=FALSE}
#Creating a dataframe with the data divided by Minutes Played
PF_Filter_MP <- select(PF_Data,FG:DRB.Diff) 

PF_Stats_MP <- PF_Filter_MP %>% mutate_if(is.numeric, funs(./PF_Data$MP))

PF_Data_MP <- PF_Stats_MP %>%
            mutate(FG.Diff = abs(PF_Stats_MP$FG - median(PF_Stats_MP$FG)), 
                   FGA.Diff = abs(PF_Stats_MP$FGA - median(PF_Stats_MP$FGA)),
                   X3P.Diff = abs(PF_Stats_MP$X3P - median(PF_Stats_MP$X3P)),
                   X3PA.Diff = abs(PF_Stats_MP$X3PA- median(PF_Stats_MP$X3PA)),
                   X2P.Diff = abs(PF_Stats_MP$X2P - median(PF_Stats_MP$X2P)),
                   X2PA.Diff =abs(PF_Stats_MP$X2PA - median(PF_Stats_MP$X2PA)),
                   FT.Diff = abs(PF_Stats_MP$FT - median(PF_Stats_MP$FT)),
                   FTA.Diff =abs(PF_Stats_MP$FTA - median(PF_Stats_MP$FTA)),
                   TRB.Diff =abs(PF_Stats_MP$TRB - median(PF_Stats_MP$TRB)),
                   AST.Diff =abs(PF_Stats_MP$AST - median(PF_Stats_MP$AST)), 
                   STL.Diff =abs(PF_Stats_MP$STL - median(PF_Stats_MP$STL)), 
                   BLK.Diff =abs(PF_Stats_MP$BLK - median(PF_Stats_MP$BLK)),
                   TOV.Diff =abs(PF_Stats_MP$TOV - median(PF_Stats_MP$TOV)),
                   PF.Diff =abs(PF_Stats_MP$PF - median(PF_Stats_MP$PF)),
                   PTS.Diff =abs(PF_Stats_MP$PTS - median(PF_Stats_MP$PTS)),
                   FG_P.Diff =abs(PF_Stats_MP$FG_P - median(PF_Stats_MP$FG_P)),
                   FT_P.Diff =abs(PF_Stats_MP$FT_P - median(PF_Stats_MP$FT_P)),
                   X3P_P.Diff =abs(PF_Stats_MP$X3P_P - median(PF_Stats_MP$X3P_P)),
                   X2P_P.Diff =abs(PF_Stats_MP$X2P_P - median(PF_Stats_MP$X2P_P)),
                   eFG_P.Diff =abs(PF_Stats_MP$eFG_P - median(PF_Stats_MP$eFG_P)), 
                   ORB.Diff = abs(PF_Stats_MP$ORB - median(PF_Stats_MP$ORB)),
                   DRB.Diff = abs(PF_Stats_MP$DRB - median(PF_Stats_MP$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
PF_Data_MP <- mutate(PF_Data_MP, 
                    Player = PF_Data$Player, 
                    Pos = PF_Data$Pos, 
                    Tm = PF_Data$Tm, 
                    Age = PF_Data$Age, 
                    Age.Diff = PF_Data$Age.Diff, 
                    G = PF_Data$G, 
                    G.Diff = PF_Data$G.Diff, 
                    GS = PF_Data$GS, 
                    GS.Diff = PF_Data$GS.Diff,
                    MP = PF_Data$MP, 
                    MP.Diff = PF_Data$MP.Diff
                    )

PF_Data_MP <- PF_Data_MP %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

```{r c.overall, echo=FALSE}
#Finding the Stats for PGs
C_Data <- BRTotal %>% filter(Pos == "C") %>% drop_na()
# Adding the absolute value Differentials for each player from the medians
C_Data <- C_Data %>%
            mutate(Age.Diff = abs(C_Data$Age - median(C_Data$Age)),
                   G.Diff = abs(C_Data$G - median(C_Data$G)),
                   GS.Diff = abs(C_Data$GS - median(C_Data$GS)),
                   MP.Diff = abs(C_Data$MP - median(C_Data$MP)),
                   FG.Diff = abs(C_Data$FG - median(C_Data$FG)), 
                   FGA.Diff = abs(C_Data$FGA - median(C_Data$FGA)),
                   X3P.Diff = abs(C_Data$X3P - median(C_Data$X3P)),
                   X3PA.Diff = abs(C_Data$X3PA- median(C_Data$X3PA)),
                   X2P.Diff = abs(C_Data$X2P - median(C_Data$X2P)),
                   X2PA.Diff =abs(C_Data$X2PA - median(C_Data$X2PA)),
                   FT.Diff = abs(C_Data$FT - median(C_Data$FT)),
                   FTA.Diff =abs(C_Data$FTA - median(C_Data$FTA)),
                   TRB.Diff =abs(C_Data$TRB - median(C_Data$TRB)),
                   AST.Diff =abs(C_Data$AST - median(C_Data$AST)), 
                   STL.Diff =abs(C_Data$STL - median(C_Data$STL)), 
                   BLK.Diff =abs(C_Data$BLK - median(C_Data$BLK)),
                   TOV.Diff =abs(C_Data$TOV - median(C_Data$TOV)),
                   PF.Diff =abs(C_Data$PF - median(C_Data$PF)),
                   PTS.Diff =abs(C_Data$PTS - median(C_Data$PTS)),
                   FG_P.Diff =abs(C_Data$FG_P - median(C_Data$FG_P)),
                   FT_P.Diff =abs(C_Data$FT_P - median(C_Data$FT_P)),
                   X3P_P.Diff =abs(C_Data$X3P_P - median(C_Data$X3P_P)),
                   X2P_P.Diff =abs(C_Data$X2P_P - median(C_Data$X2P_P)),
                   eFG_P.Diff =abs(C_Data$eFG_P - median(C_Data$eFG_P)), 
                   ORB.Diff = abs(C_Data$ORB - median(C_Data$ORB)),
                   DRB.Diff = abs(C_Data$DRB - median(C_Data$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
C_Data <- C_Data %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

```{r c.g, echo=FALSE}
#Creating a dataframe with the data divided by Games Played
C_Filter_G <- select(C_Data,MP:DRB.Diff) 

C_Stats_G <- C_Filter_G %>% mutate_if(is.numeric, funs(./C_Data$G))

C_Data_G <- C_Stats_G %>%
            mutate(MP.Diff = abs(C_Stats_G$MP - median(C_Stats_G$MP)),
                   FG.Diff = abs(C_Stats_G$FG - median(C_Stats_G$FG)), 
                   FGA.Diff = abs(C_Stats_G$FGA - median(C_Stats_G$FGA)),
                   X3P.Diff = abs(C_Stats_G$X3P - median(C_Stats_G$X3P)),
                   X3PA.Diff = abs(C_Stats_G$X3PA- median(C_Stats_G$X3PA)),
                   X2P.Diff = abs(C_Stats_G$X2P - median(C_Stats_G$X2P)),
                   X2PA.Diff =abs(C_Stats_G$X2PA - median(C_Stats_G$X2PA)),
                   FT.Diff = abs(C_Stats_G$FT - median(C_Stats_G$FT)),
                   FTA.Diff =abs(C_Stats_G$FTA - median(C_Stats_G$FTA)),
                   TRB.Diff =abs(C_Stats_G$TRB - median(C_Stats_G$TRB)),
                   AST.Diff =abs(C_Stats_G$AST - median(C_Stats_G$AST)), 
                   STL.Diff =abs(C_Stats_G$STL - median(C_Stats_G$STL)), 
                   BLK.Diff =abs(C_Stats_G$BLK - median(C_Stats_G$BLK)),
                   TOV.Diff =abs(C_Stats_G$TOV - median(C_Stats_G$TOV)),
                   PF.Diff =abs(C_Stats_G$PF - median(C_Stats_G$PF)),
                   PTS.Diff =abs(C_Stats_G$PTS - median(C_Stats_G$PTS)),
                   FG_P.Diff =abs(C_Stats_G$FG_P - median(C_Stats_G$FG_P)),
                   FT_P.Diff =abs(C_Stats_G$FT_P - median(C_Stats_G$FT_P)),
                   X3P_P.Diff =abs(C_Stats_G$X3P_P - median(C_Stats_G$X3P_P)),
                   X2P_P.Diff =abs(C_Stats_G$X2P_P - median(C_Stats_G$X2P_P)),
                   eFG_P.Diff =abs(C_Stats_G$eFG_P - median(C_Stats_G$eFG_P)), 
                   ORB.Diff = abs(C_Stats_G$ORB - median(C_Stats_G$ORB)),
                   DRB.Diff = abs(C_Stats_G$DRB - median(C_Stats_G$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
C_Data_G <- mutate(C_Data_G, 
                    Player = C_Data$Player, 
                    Pos = C_Data$Pos, 
                    Tm = C_Data$Tm, 
                    Age = C_Data$Age, 
                    Age.Diff = C_Data$Age.Diff, 
                    G = C_Data$G, 
                    G.Diff = C_Data$G.Diff, 
                    GS = C_Data$GS, 
                    GS.Diff = C_Data$GS.Diff
                    )

C_Data_G <- C_Data_G %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```

```{r c.mp, echo=FALSE}
#Creating a dataframe with the data divided by Minutes Played
C_Filter_MP <- select(C_Data,FG:DRB.Diff) 

C_Stats_MP <- C_Filter_MP %>% mutate_if(is.numeric, funs(./C_Data$MP))

C_Data_MP <- C_Stats_MP %>%
            mutate(FG.Diff = abs(C_Stats_MP$FG - median(C_Stats_MP$FG)), 
                   FGA.Diff = abs(C_Stats_MP$FGA - median(C_Stats_MP$FGA)),
                   X3P.Diff = abs(C_Stats_MP$X3P - median(C_Stats_MP$X3P)),
                   X3PA.Diff = abs(C_Stats_MP$X3PA- median(C_Stats_MP$X3PA)),
                   X2P.Diff = abs(C_Stats_MP$X2P - median(C_Stats_MP$X2P)),
                   X2PA.Diff = abs(C_Stats_MP$X2PA - median(C_Stats_MP$X2PA)),
                   FT.Diff = abs(C_Stats_MP$FT - median(C_Stats_MP$FT)),
                   FTA.Diff = abs(C_Stats_MP$FTA - median(C_Stats_MP$FTA)),
                   TRB.Diff = abs(C_Stats_MP$TRB - median(C_Stats_MP$TRB)),
                   AST.Diff = abs(C_Stats_MP$AST - median(C_Stats_MP$AST)), 
                   STL.Diff = abs(C_Stats_MP$STL - median(C_Stats_MP$STL)), 
                   BLK.Diff = abs(C_Stats_MP$BLK - median(C_Stats_MP$BLK)),
                   TOV.Diff = abs(C_Stats_MP$TOV - median(C_Stats_MP$TOV)),
                   PF.Diff = abs(C_Stats_MP$PF - median(C_Stats_MP$PF)),
                   PTS.Diff = abs(C_Stats_MP$PTS - median(C_Stats_MP$PTS)),
                   FG_P.Diff = abs(C_Stats_MP$FG_P - median(C_Stats_MP$FG_P)),
                   FT_P.Diff = abs(C_Stats_MP$FT_P - median(C_Stats_MP$FT_P)),
                   X3P_P.Diff = abs(C_Stats_MP$X3P_P - median(C_Stats_MP$X3P_P)),
                   X2P_P.Diff = abs(C_Stats_MP$X2P_P - median(C_Stats_MP$X2P_P)),
                   eFG_P.Diff = abs(C_Stats_MP$eFG_P - median(C_Stats_MP$eFG_P)), 
                   ORB.Diff = abs(C_Stats_MP$ORB - median(C_Stats_MP$ORB)),
                   DRB.Diff = abs(C_Stats_MP$DRB - median(C_Stats_MP$DRB))
                   )
# Restructuring of Columns to make columns related to one another next to one another
C_Data_MP <- mutate(C_Data_MP, 
                    Player = C_Data$Player, 
                    Pos = C_Data$Pos, 
                    Tm = C_Data$Tm, 
                    Age = C_Data$Age, 
                    Age.Diff = C_Data$Age.Diff, 
                    G = C_Data$G, 
                    G.Diff = C_Data$G.Diff, 
                    GS = C_Data$GS, 
                    GS.Diff = C_Data$GS.Diff,
                    MP = C_Data$MP, 
                    MP.Diff = C_Data$MP.Diff
                    )

C_Data_MP <- Data_MP %>%
  select(Player, Pos, Tm, Age, Age.Diff, G, G.Diff, GS, GS.Diff, MP, MP.Diff, FG, FG.Diff, FGA, FGA.Diff, X3P, X3P.Diff, X3PA, X3PA.Diff, X2P, X2P.Diff, X2PA, X2PA.Diff, FT, FT.Diff, FTA, FTA.Diff, TRB, TRB.Diff, AST, AST.Diff, STL, STL.Diff, BLK, BLK.Diff, TOV, TOV.Diff, PF, PF.Diff, PTS, PTS.Diff, FG_P, FG_P.Diff, FT_P, FT_P.Diff, X3P_P, X3P_P.Diff, X2P_P, X2P_P.Diff, eFG_P, eFG_P.Diff, ORB, ORB.Diff, DRB, DRB.Diff)
```
